import github3, arrow
import os, sys, datetime, argparse, json, re, shutil
import itertools
from pathlib import Path
from bokeh.plotting import figure, output_file, show
from bokeh.layouts import gridplot, row
from bokeh.palettes import Category10 as palette
from functools import reduce
import pandas as pd

def get_raw_pull_data(organization, repository, token, url=None):
    if url:
        client = github3.enterprise_login(token=token, url=url)
    else:
        client = github3.login(token=token)
    repo = client.repository(organization, repository)
    pull_requests = repo.pull_requests(state='closed')

    result = list(map(lambda x: x.as_dict(), pull_requests))
    return result


def data_to_graph_params(data, width, name_map):
    def colors():
        yield from itertools.cycle(palette[10])
        
    color = colors()
    line_result = {}
    bar_result = {}
    for param in data:
        match = re.match('([0-9][0-9])th', param)
        x = []
        y = []
        for key in sorted(data[param].keys()):
            x.append(key)
            y.append(data[param][key])
        if match:
            line_result[param] = {
                'legend': "{}%-tile time".format(match[1]),
                'line_color': next(color),
                'x': x,
                'y': y
            }
        else:
            bar_result[param] = {
                'width': width,
                'legend': name_map[param],
                'x': x,
                'top': y,
                'fill_color': next(color)
            }
    return line_result, bar_result


def graph(line_data, bar_data, repository_name, frame, x_range=None, y_range=None):
    line_chart = figure(
        title="Pull Request Data for %s, Aggregated by %s" % (repository_name.capitalize(), frame.capitalize()),
        x_axis_label="Date", 
        y_axis_label='Time to close PR (days)', 
        x_axis_type="datetime")
    if x_range is not None:
        line_chart.x_range = x_range
    if y_range is not None:
        line_chart.y_range = y_range

    bar_chart = figure(
        title="Pull Request Data for %s, Aggregated by %s" % (repository_name.capitalize(), frame.capitalize()), 
        x_axis_label='Date', 
        x_axis_type="datetime", 
        x_range=line_chart.x_range)
    
    for key in line_data.keys():
        line_chart.line(line_width=2, **line_data[key])
    
    for key in bar_data.keys():
        bar_chart.vbar(**bar_data[key])
    
    line_chart.legend.click_policy = 'hide'

    return [line_chart, bar_chart]

def cli():
    parser = argparse.ArgumentParser(description='A tool to visualize Github data')

    parser.add_argument('-m', '--month', dest='frame', action='store_const', const='month', default='week', help='aggregate data by month (default: by week)')
    cache_group = parser.add_mutually_exclusive_group()
    flush_group = parser.add_mutually_exclusive_group()
    url_group = parser.add_mutually_exclusive_group()
    token_group = parser.add_mutually_exclusive_group()

    cache_group.add_argument('-b', '--build-cache', dest='force_build_cache', action='store_true', help='Force build the cache, overriding any currently cached data')
    cache_group.add_argument('--no-cache', dest='fetch_no_cache', action='store_true', help='Force fetch the data but do not write it to a local cache')
    cache_group.add_argument('--cache-no-render', dest='fetch_no_render', action='store_true', help='Force build the cache but do not render the graph')

    flush_group.add_argument('--flush-all', action='store_true', help='Flushes all cached data and html files without executing the script')
    flush_group.add_argument('--flush-all-html', dest='flush_html', action='store_true', help='Flushes all html files generated by OctoViz without executing the script')
    flush_group.add_argument('--flush-all-cache', dest='flush_cache', action='store_true', help='Flushes all cached data files without executing the script')
    flush_group.add_argument('-f', '--flush', action='store_true', help='Flushes the cache for the repositories specified. Deletes only files, not folders')
    flush_group.add_argument('-rm', '--remove', action='store_true', help='Flushes all cached data after execution. Does not delete html files.')
    
    url_group.add_argument('-u', '--url', action='store', nargs=1, help='The url to use (if in a corporate environment)', default=[None])
    url_group.add_argument('-g', '--github', action='store_true', help='Force connect to Github\'s servers instead of any set by environment variable')

    token_group.add_argument('-tv', '--token-value', action='store', nargs=1, help='OAuth token to use (overrides environment-specified token)', default=[None])
    token_group.add_argument('-tn', '--token-name', action='store', nargs=1, help='Specify the name of the environment variable to use for the token', default=[None])
    
    parser.add_argument('-x', '--link-x-axis', dest='link_x', action='store_true', help='Link the x-axis of all generated graphs')
    parser.add_argument('-y', '--link-y-axis', dest='link_y', action='store_true', help='Link the y-axis of all line graphs')
    parser.add_argument('-n', '--name', action='store', nargs=1, help='Name of the output file')
    parser.add_argument('repos', metavar='repository', nargs='*', help='Repository to pull data from')

    parser.epilog = 'All files are stored under ~/.octoviz directory. If no output file name has been specified, OctoViz will override previous render'

    args = parser.parse_args()

    home_dir = str(Path.home())
    octoviz_dir = lambda x="": '%s/.octoviz%s' % (home_dir, "/%s" % x if x else "")

    if not os.path.exists(octoviz_dir()):
        os.mkdir(octoviz_dir())

    if len(args.repos) == 0 and not (args.flush_all or args.flush_cache or args.flush_html):
        parser.error('Must specify repositories or one of the --flush-all flag!\n')
        sys.exit(1)

    if args.flush_all or args.flush or args.flush_cache or args.flush_html:
        if args.flush_all or args.flush_cache:
            shutil.rmtree(octoviz_dir('cache'), ignore_errors=True)
        if args.flush_all or args.flush_html:
            shutil.rmtree(octoviz_dir('html'), ignore_errors=True)
        if args.flush:
            for repo in args.repos:
                if os.path.exists(octoviz_dir('cache/%s.json' % repo)):
                    os.remove(octoviz_dir('cache/%s.json' % repo))
        sys.exit(0)  # Exit after flushing


    if args.token_value[0]:
        token = args.token_value[0]
    elif args.token_name[0]:
        token = os.getenv(args.token_name[0])
    else:
        token = os.getenv('GITHUB_API_TOKEN')
    
    if args.url[0]:
        url = args.url[0]
    if args.github:
        url = None
    else:
        url = os.getenv('GITHUB_URL')
    
    pull_data = []
    chart_data = []
    x_axis = None
    y_axis = None
    frame_data = lambda func, iterable: list(map(func, iterable))
    stats = lambda group: {'25th': group.quantile(0.25), '50th': group.median(), '90th': group.quantile(0.9), 'count': group.count()}

    build_cache_flags = args.fetch_no_cache or args.force_build_cache or args.fetch_no_render

    if args.name:
        file_name = octoviz_dir('html/%s.html' % args.name[0])
    else:
        file_name = octoviz_dir('html/octoviz.html')
    
    if not (args.fetch_no_render or args.flush or args.flush_all):
        if not os.path.exists(octoviz_dir('html')):
            os.mkdir(octoviz_dir('html'))
        output_file(file_name)

    for repository in args.repos:
        org, repo = repository.split('/') 

        # Build cache if force or if the cache does not exist
        if build_cache_flags or not os.path.exists(octoviz_dir('cache/%s/%s.json' % (org, repo))):
            if not os.path.exists(octoviz_dir('cache')):
                os.mkdir(octoviz_dir('cache'))
            if not os.path.exists(octoviz_dir('cache/%s' % org)):
                os.mkdir(octoviz_dir('cache/%s' % org))

            pull_data = get_raw_pull_data(org, repo, token, url)

            
            if not args.fetch_no_cache:
                with open(octoviz_dir('cache/%s.json' % repository), "w") as f:
                    json.dump(pull_data, f)
                
                if args.fetch_no_render:
                    continue

        # Read from cache files if they exist and not force-rebuild
        else:
            with open(octoviz_dir('cache/%s.json' % repository), "r") as f:
                pull_data = json.load(f)
        
        # Build pandas frame
        frame = pd.DataFrame(
            {
                'Pull Number': frame_data(lambda x: x['number'], pull_data),
                'Created At': frame_data(lambda x: arrow.get(x['created_at']).floor(args.frame).datetime, pull_data),
                'Closed At': frame_data(lambda x: arrow.get(x['closed_at']).floor(args.frame).datetime, pull_data),
                'User': frame_data(lambda x: x['user']['login'], pull_data),
                'Lifetime': frame_data(lambda x: (arrow.get(x['closed_at']) - arrow.get(x['created_at'])).total_seconds()/3600/24, pull_data)
            }
        )
        
        bar_width = (arrow.now().ceil(args.frame) - arrow.now().floor(args.frame)).total_seconds() * 800
        data = frame['Lifetime'].groupby(frame['Closed At']).apply(stats).unstack().to_dict()
        line, bar = data_to_graph_params(data, bar_width, {'count': 'PRs Completed'})
        chart_data.append(graph(line, bar, repo, args.frame, x_axis, y_axis))

        if args.link_x:
            x_axis = chart_data[-1][0].x_range
        if args.link_y:
            y_axis = chart_data[-1][0].y_range

    
    if args.remove:
        shutil.rmtree(octoviz_dir('cache'), ignore_errors=True)

    if not args.fetch_no_render:
        show(gridplot(chart_data))


if __name__ == "__main__":
    cli()
    